# Generated by Django 4.1 on 2022-08-27 11:11

from django.db import migrations, models
import multiplefile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='File ID')),
                ('upload_file', models.FileField(blank=True, null=True, storage=multiplefile.models.OverwriteStorage(), upload_to=multiplefile.models.file_directory_path_instance, verbose_name='Upload File')),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
            ],
        ),
    ]
