# Generated by Django 4.1 on 2022-08-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_users_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
